### ISSUE TITLE
Update ansible galaxy version

### ISSUE THREAD

**Issue by Dutchy-** [nephelaiio/ansible-role-unifi-controller#2]
I just installed the version from ansible galaxy and I wondered why it is not installing my java packages... It contains this line:

`when: ansible_architecture == "armv7l"`

Seems like this is an old version? I can install from git in the meantime but maybe you can release a new version?

**Comment by teddyphreak** [comment]
Hi, this was a specific workaround to install on raspberry pi devices, I'm happy to apply any changes required if you can provide details on your specific use case

**Comment by plasticrake** [comment]
@teddyphreak, the version on galaxy is missing the `apt-transport-https` package and is failing  for me on a new Debian install. If the galaxy version was updated to what is in the repo it would work. In addition to the original issue which does not install java on non arm platforms (but the version on the repo will)

**Comment by Dutchy-** [comment]
Exactly that, the git version works for me, no changes required. I only need an update to the galaxy version :)

**Comment by teddyphreak** [comment]
Galaxy tag 2.0.1 will be published as part of https://travis-ci.org/nephelaiio/ansible-role-unifi-controller/builds/602155420
