### ISSUE TITLE
Add ca-certificates in package dependencies 

### ISSUE THREAD

**Issue by hlm-acc** [nephelaiio/ansible-role-unifi-controller#4]
Hi, thanks for this, very useful !

A small improvement would be to add **ca-certificates** in package dependencies, was needed to install unifi smoothly inside Debian 9 LXC.

> roles/unifi/defaults/main.yml

```
unifi_package_dependencies:
  - gnupg
  - apt-transport-https
  - ca-certificates
```

**Comment by teddyphreak** [comment]
Thank you, I'll add the package to the list shortly
